# Generated by Django 2.0.1 on 2018-02-03 16:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('\\d{6}')], verbose_name='代表者番号')),
                ('first_name', models.CharField(max_length=15, verbose_name='代表者氏名(姓)')),
                ('second_name', models.CharField(max_length=15, verbose_name='代表者氏名(名)')),
                ('first_name_kana', models.CharField(max_length=30, verbose_name='代表者氏名（セイ）')),
                ('second_name_kana', models.CharField(max_length=30, verbose_name='代表者氏名（メイ）')),
                ('zip_code', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator('\\d{7}')], verbose_name='郵便番号')),
                ('address', models.CharField(max_length=255, verbose_name='住所')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('\\d{3,11}')], verbose_name='電話番号')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='申込日')),
                ('rental_start_date', models.DateField(verbose_name='レンタル開始日')),
                ('rental_end_date', models.DateField(null=True, verbose_name='レンタル終了日')),
                ('kind', models.CharField(max_length=10, verbose_name='レンタル種目')),
                ('item_summary', models.CharField(max_length=10, verbose_name='レンタルセット内容')),
                ('base_fee', models.IntegerField(verbose_name='基本合計金額')),
                ('discount', models.IntegerField(verbose_name='割引金額')),
                ('total_fee', models.IntegerField(verbose_name='合計金額')),
                ('memo', models.TextField(max_length=50, verbose_name='備考')),
            ],
        ),
        migrations.CreateModel(
            name='RentalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=20, verbose_name='レンタル用品')),
                ('item_id', models.CharField(max_length=10, null=True, verbose_name='レンタル品ID')),
                ('rental', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.Rental')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_number', models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{1}\\d{6}')], verbose_name='利用者番号')),
                ('first_name', models.CharField(max_length=15, verbose_name='利用者氏名(姓)')),
                ('second_name', models.CharField(max_length=15, verbose_name='利用者氏名(名)')),
                ('first_name_kana', models.CharField(max_length=30, verbose_name='利用者氏名（セイ）')),
                ('second_name_kana', models.CharField(max_length=30, verbose_name='利用者氏名（メイ）')),
                ('age', models.IntegerField(verbose_name='年齢')),
                ('height', models.IntegerField(verbose_name='身長')),
                ('wight', models.IntegerField(verbose_name='体重')),
                ('foot', models.CharField(max_length=4, verbose_name='足サイズ')),
                ('memo', models.TextField(max_length=255, null=True, verbose_name='備考')),
                ('last_use_date', models.DateField(verbose_name='最終利用日')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.CustomerInfo')),
            ],
        ),
        migrations.AddField(
            model_name='rental',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.UserInfo'),
        ),
    ]
