# Generated by Django 2.0.1 on 2018-02-10 13:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='memo',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_number',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{1}\\d{7}')], verbose_name='利用者番号'),
        ),
    ]
