# Generated by Django 2.0.1 on 2018-02-10 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_auto_20180210_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_number',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('[A-Z]{1}\\d{7}')], verbose_name='利用者番号'),
        ),
    ]
