# Generated by Django 2.0.1 on 2018-02-24 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0007_rentalmenumaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalMenuKindMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind_id', models.CharField(max_length=2, verbose_name='レンタル種目ID')),
                ('kind_name', models.CharField(max_length=10, verbose_name='レンタル種目名')),
            ],
        ),
        migrations.AlterField(
            model_name='rentalmenumaster',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.RentalMenuKindMaster'),
        ),
    ]
