# Generated by Django 2.0.1 on 2018-02-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0008_auto_20180225_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalmenukindmaster',
            name='id',
        ),
        migrations.AlterField(
            model_name='rentalmenukindmaster',
            name='kind_id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='レンタル種目ID'),
        ),
    ]
