# Generated by Django 2.0.1 on 2018-02-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0009_auto_20180225_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalmenumaster',
            name='kind',
            field=models.CharField(max_length=2, verbose_name='レンタル種目ID'),
        ),
    ]
