# Generated by Django 2.0.1 on 2018-04-13 15:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0011_auto_20180225_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateField(verbose_name='レンタル日')),
                ('base_fee', models.IntegerField(verbose_name='金額')),
                ('discount', models.IntegerField(null=True, verbose_name='割引金額')),
                ('total_fee', models.IntegerField(verbose_name='割引後金額')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contract.CustomerInfo')),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rental_date',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='user',
        ),
        migrations.RemoveField(
            model_name='rentalmenumaster',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rentalmenumaster',
            name='kind',
        ),
        migrations.AddField(
            model_name='rental',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年齢'),
        ),
        migrations.AddField(
            model_name='rental',
            name='first_name',
            field=models.CharField(max_length=15, null=True, verbose_name='利用者氏名(姓)'),
        ),
        migrations.AddField(
            model_name='rental',
            name='first_name_kana',
            field=models.CharField(max_length=30, null=True, verbose_name='利用者氏名（セイ）'),
        ),
        migrations.AddField(
            model_name='rental',
            name='foot',
            field=models.CharField(max_length=4, null=True, verbose_name='足サイズ'),
        ),
        migrations.AddField(
            model_name='rental',
            name='height',
            field=models.IntegerField(null=True, verbose_name='身長'),
        ),
        migrations.AddField(
            model_name='rental',
            name='second_name',
            field=models.CharField(max_length=15, null=True, verbose_name='利用者氏名(名)'),
        ),
        migrations.AddField(
            model_name='rental',
            name='second_name_kana',
            field=models.CharField(max_length=30, null=True, verbose_name='利用者氏名（メイ）'),
        ),
        migrations.AddField(
            model_name='rental',
            name='user_number',
            field=models.CharField(max_length=7, null=True, validators=[django.core.validators.RegexValidator('[A-Z]{1}\\d{6}')], verbose_name='利用者番号'),
        ),
        migrations.AddField(
            model_name='rental',
            name='wight',
            field=models.IntegerField(null=True, verbose_name='体重'),
        ),
        migrations.AddField(
            model_name='rentalmenumaster',
            name='kind_id',
            field=models.CharField(default=1, max_length=2, primary_key=True, serialize=False, verbose_name='レンタル種目ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rentalmenumaster',
            name='kind_name',
            field=models.CharField(default=1, max_length=10, verbose_name='レンタル種目名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='base_fee',
            field=models.IntegerField(verbose_name='基本料金'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='discount',
            field=models.IntegerField(null=True, verbose_name='割引金額'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='item_summary',
            field=models.CharField(max_length=20, verbose_name='レンタルセット内容'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='memo',
            field=models.TextField(max_length=50, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='total_fee',
            field=models.IntegerField(verbose_name='小計'),
        ),
        migrations.AlterField(
            model_name='rentalmenumaster',
            name='base_fee',
            field=models.IntegerField(verbose_name='基本金額'),
        ),
        migrations.DeleteModel(
            name='RentalMenuKindMaster',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(default=20, on_delete=django.db.models.deletion.PROTECT, to='contract.ContractInfo'),
            preserve_default=False,
        ),
    ]
