# Generated by Django 2.0.1 on 2018-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0014_auto_20180414_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalinfo',
            old_name='customer',
            new_name='contract',
        ),
        migrations.AlterField(
            model_name='contractinfo',
            name='discount',
            field=models.IntegerField(blank=True, verbose_name='割引金額'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='discount',
            field=models.IntegerField(blank=True, verbose_name='割引金額'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='first_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='利用者氏名(姓)'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='first_name_kana',
            field=models.CharField(blank=True, max_length=30, verbose_name='利用者氏名（セイ）'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='foot',
            field=models.CharField(blank=True, max_length=4, verbose_name='足サイズ'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='height',
            field=models.IntegerField(blank=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='memo',
            field=models.TextField(blank=True, max_length=50, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='rental_end_date',
            field=models.DateField(blank=True, verbose_name='レンタル終了日'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='second_name',
            field=models.CharField(blank=True, max_length=15, verbose_name='利用者氏名(名)'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='second_name_kana',
            field=models.CharField(blank=True, max_length=30, verbose_name='利用者氏名（メイ）'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='wight',
            field=models.IntegerField(blank=True, verbose_name='体重'),
        ),
        migrations.AlterField(
            model_name='rentalitem',
            name='item_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='レンタル品ID'),
        ),
    ]
