# Generated by Django 2.0.1 on 2018-04-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0016_auto_20180420_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinfo',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='割引金額'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='身長'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='レンタル終了日'),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='wight',
            field=models.IntegerField(blank=True, null=True, verbose_name='体重'),
        ),
    ]
