# Generated by Django 2.0.1 on 2018-04-20 14:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0017_auto_20180420_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinfo',
            name='user_number',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('[A-Z]{1}\\d{6}')], verbose_name='利用者番号'),
        ),
    ]
