# Generated by Django 2.0.1 on 2018-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0018_auto_20180420_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractinfo',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='割引金額'),
        ),
    ]
