# Generated by Django 2.0.1 on 2018-06-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0021_auto_20180501_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalinfo',
            name='item_summary',
        ),
        migrations.RemoveField(
            model_name='rentalinfo',
            name='kind',
        ),
        migrations.AddField(
            model_name='rentalinfo',
            name='rental_menu',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='contract.RentalMenuMaster'),
            preserve_default=False,
        ),
    ]
